### ISSUE TITLE
Implement ACLs

### ISSUE THREAD

**Issue by purplefox** [spirit-labs/tektite#211] opened 2024-08-12 16:31 UTC
We will implement ACL (access control lists) in Tektite, to control access to Tektite resources like topics and streams. They will work in a similar way to Kafka ACLs, and the `kafka-acls.sh` command line tool should be usable to manage them.

https://docs.confluent.io/platform/current/security/authorization/acls/overview.html

**Comment by devguyio** [comment] 2024-08-25 13:12
Duplicate of #232

**Closed by devguyio** 2024-08-25 13:12 UTC
